spring:
  datasource:
    url: jdbc:mysql://local.home.com:3306/video
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8080
logging:
  level:
    root: INFO
    com.home.video: DEBUG